name: Databricks Asset Bundle Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Set up Databricks environment variables
        env:
          DATABRICKS_HOST: ${{ secrets.WORKSPACE_URL }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}
        run: |
          echo "DATABRICKS_HOST=$DATABRICKS_HOST" >> $GITHUB_ENV
          echo "DATABRICKS_TOKEN=$DATABRICKS_TOKEN" >> $GITHUB_ENV

      - name: Create Databricks Asset Bundle
        run: |
          zip -r /tmp/asset_bundle.zip .

      - name: Deploy to Dev
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN_DEV }}" -H "Content-Type: application/json" -d '{"path": "/src/main/extract", "overwrite": true}' "${{ secrets.WORKSPACE_URL }}/api/2.0/workspace/import" --data-binary @/tmp/asset_bundle.zip
