name: Deploy Databricks Notebooks
on:
  push:
    branches:
      - main
jobs:
  deploy-databricks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Deploy to Databricks
        uses: databricks/terraform-action@v1
        with:
          token: ${{ ${{ secrets.DATABRICKS_TOKEN_DEV }} }}
          workspace-url: ${{ secrets.WORKSPACE_URL }}
          notebooks: |
            [
              {
                "path": "/Repos/malik.shaik@costrategix.com/dbx-ci-cd/src/main/extract",
                "format": "SOURCE"
              },
              {
                "path": "/Repos/malik.shaik@costrategix.com/dbx-ci-cd/src/main/transform",
                "format": "SOURCE"
              }
            ]
