name: Azure Databricks Job Submission

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Databricks CLI
        run: pip install databricks-cli

      # Step 2: Create Databricks job cluster
      - name: Create Databricks job cluster
        run: |
          databricks clusters create --json-file cluster_config.json

      # Step 3: Authenticate with Databricks if needed
      - name: Authenticate with Databricks
        run: |
          databricks workspace configure --url ${{ secrets.WORKSPACE_URL }} && databricks configure --token ${{ secrets.DATABRICKS_TOKEN_DEV }} 

      # Step 4: Copy source code to Databricks
      - name: Copy source code to Databricks
        run: |
          databricks workspace import_dir . /Repos/release
        
      # Step 5: Submit jobs
      - name: Submit Databricks jobs
        run: |
          databricks jobs create --yml-file jobs/etl-workflow.yml
