name: Deploy to Databricks

on:
  push:
    branches:
      - main # Adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Write to .databrickscfg
        run: |
          echo "[DEFAULT]" > $HOME/.databrickscfg
          echo "host = $DATABRICKS_HOST" >> $HOME/.databrickscfg
          echo "token = $DATABRICKS_TOKEN" >> $HOME/.databrickscfg

      - name: Run databricks bundle deploy
        env:
          DATABRICKS_HOST: https://adb-6399455296052405.5.azuredatabricks.net
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}
          DATABRICKS_BUNDLE_ENV: dev
        run: databricks bundle deploy --debug
